// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4r5IICReZTnCi2lxTs6uUaf-f9AJcueM',
    appId: '1:827722876342:web:1c28c65cd104b80779ed17',
    messagingSenderId: '827722876342',
    projectId: 'fasum1-8c771',
    authDomain: 'fasum1-8c771.firebaseapp.com',
    databaseURL: 'https://fasum1-8c771-default-rtdb.firebaseio.com',
    storageBucket: 'fasum1-8c771.appspot.com',
    measurementId: 'G-0HXXHP4C24',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEUMoH876L8Kt6I0SuBMxkdrhRR9sNo-A',
    appId: '1:827722876342:android:ba2224d8c6e5220f79ed17',
    messagingSenderId: '827722876342',
    projectId: 'fasum1-8c771',
    databaseURL: 'https://fasum1-8c771-default-rtdb.firebaseio.com',
    storageBucket: 'fasum1-8c771.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB79QDXeiKHFpopZCmoFBLXvW5Mi0dw8fY',
    appId: '1:827722876342:ios:4632f48ebb80a82e79ed17',
    messagingSenderId: '827722876342',
    projectId: 'fasum1-8c771',
    databaseURL: 'https://fasum1-8c771-default-rtdb.firebaseio.com',
    storageBucket: 'fasum1-8c771.appspot.com',
    iosBundleId: 'com.example.fasumAppls',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB79QDXeiKHFpopZCmoFBLXvW5Mi0dw8fY',
    appId: '1:827722876342:ios:9f415f1379876ecb79ed17',
    messagingSenderId: '827722876342',
    projectId: 'fasum1-8c771',
    databaseURL: 'https://fasum1-8c771-default-rtdb.firebaseio.com',
    storageBucket: 'fasum1-8c771.appspot.com',
    iosBundleId: 'com.example.fasumAppls.RunnerTests',
  );
}
